"""Add hubungan field to DetailCetak

Revision ID: 669008b3740e
Revises: 9c41a24bdfdd
Create Date: 2026-01-07 20:44:26.396514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669008b3740e'
down_revision = '9c41a24bdfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_cetak', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hubungan', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_cetak', schema=None) as batch_op:
        batch_op.drop_column('hubungan')

    # ### end Alembic commands ###
