"""Add DokumenTransaksi, StatusLayananLog, and Kecamatan.is_active

Revision ID: 681050d7f9cb
Revises: 
Create Date: 2026-04-29 11:50:40.201582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681050d7f9cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_layanan_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kecamatan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status_sebelum', sa.Boolean(), nullable=False),
    sa.Column('status_sesudah', sa.Boolean(), nullable=False),
    sa.Column('alasan', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['kecamatan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dokumen_transaksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaksi_id', sa.Integer(), nullable=False),
    sa.Column('nama_file', sa.String(length=255), nullable=False),
    sa.Column('path_file', sa.String(length=512), nullable=False),
    sa.Column('tipe_file', sa.String(length=20), nullable=False),
    sa.Column('ukuran_file', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaksi_id'], ['transaksi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kecamatan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('kecamatan', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    op.drop_table('dokumen_transaksi')
    op.drop_table('status_layanan_log')
    # ### end Alembic commands ###
