"""Add status_cetak and keterangan_gagal to DetailCetak

Revision ID: cc4d72cf5a18
Revises: 669008b3740e
Create Date: 2026-01-08 11:16:18.906647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4d72cf5a18'
down_revision = '669008b3740e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_cetak', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_cetak', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('keterangan_gagal', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_cetak', schema=None) as batch_op:
        batch_op.drop_column('keterangan_gagal')
        batch_op.drop_column('status_cetak')

    # ### end Alembic commands ###
