"""Add jenis_cetak and registrasi_ikd to DetailCetak

Revision ID: d1234567890a
Revises: cc4d72cf5a18
Create Date: 2026-01-08 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1234567890a'
down_revision = 'cc4d72cf5a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_cetak', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_cetak', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('registrasi_ikd', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_cetak', schema=None) as batch_op:
        batch_op.drop_column('registrasi_ikd')
        batch_op.drop_column('jenis_cetak')

    # ### end Alembic commands ###