"""Add keterangan field to Transaksi model

Revision ID: f6e9f25b26bc
Revises: d1234567890a
Create Date: 2026-01-08 15:11:11.910366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e9f25b26bc'
down_revision = 'd1234567890a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keterangan', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_column('keterangan')

    # ### end Alembic commands ###
